# Generated by Django 3.1.7 on 2021-03-19 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuarto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_hab', models.IntegerField()),
                ('categoria', models.CharField(choices=[('SC', 'SENCILLA'), ('DBL', 'DOBLE'), ('KG', 'KING'), ('QN', 'QUEEN'), ('LJ', 'LUJO')], max_length=3)),
                ('camas', models.IntegerField()),
                ('capacidad', models.IntegerField()),
            ],
        ),
    ]
